// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccidentPower: typeof import('./src/components/earthComponents/dataBubbleWindow/accidentPower.vue')['default']
    Bubble: typeof import('./src/components/earthComponents/dataBubbleWindow/bubble.vue')['default']
    Bubble2: typeof import('./src/components/earthComponents/dataBubbleWindow/bubble2.vue')['default']
    Bubble3: typeof import('./src/components/earthComponents/dataBubbleWindow/bubble3.vue')['default']
    Bubble4: typeof import('./src/components/earthComponents/dataBubbleWindow/bubble4.vue')['default']
    Description: typeof import('./src/components/earthComponents/dataBubbleWindow/description.vue')['default']
    Description2: typeof import('./src/components/earthComponents/dataBubbleWindow/description2.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    GetMessage: typeof import('./src/components/websocket/GetMessage.vue')['default']
    HomeHeader: typeof import('./src/components/homeHeader/HomeHeader.vue')['default']
    NotFound: typeof import('./src/components/content/NotFound.vue')['default']
    RightNavbar: typeof import('./src/components/rightNavbar/rightNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMessage: typeof import('./src/components/websocket/SendMessage.vue')['default']
    TaskResultDetails: typeof import('./src/components/earthComponents/dataBubbleWindow/taskResultDetails.vue')['default']
  }
}
